name: essai
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / Anim / Utils
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  carousel_slider: ^4.2.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1

  # Images / cache
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # State / routing
  provider: ^6.1.5
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  page_transition: ^2.1.0
  collection: ^1.19.1

  # Storage local
  shared_preferences: ^2.5.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  sqflite_common: ^2.5.4+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # Chiffrement
  encrypt: ^5.0.3
  crypto: ^3.0.3
  
  # Partage fichiers
  share_plus: ^7.2.2

  # Temps relatif
  timeago: ^3.7.1
  
  # HTTP requests
  http: ^1.1.0
  
  # Supabase
  supabase_flutter: ^2.3.4
  
  # Swipeable stack
  swipable_stack: ^2.0.0
  
dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/